name: Publish Docker image(i386)
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: disappear9/hentaiathome

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push for i386
        uses: docker/build-push-action@v3
        with:
          platforms: linux/i386
          push: true
          file: Dockerfile_i386
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:i386
          cache-from: type=gha,scope=i386
          cache-to: type=gha,mode=max,scope=i386
          annotations: |
            "org.opencontainers.image.source": "https://github.com/Disappear9/H-at-H-docker"
            "org.opencontainers.image.description": "Dockerfile of Hentai@Home (arm,x64,x86)"
